version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:unstable"

packages: ["php8.1-simplexml"]

config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    - "composer update"

  test:
    - "phpunit"

