name: tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: UnitTests
      run: ./kickstart.sh -e "GOOGLE_SERVICE_ACCOUNT='${{ secrets.GOOGLE_SERVICE_ACCOUNT }}'" -e "AZURE_SERVICE_ACCOUNT='${{ secrets.AZURE_SERVICE_ACCOUNT }}'" :test
  
